# Hello world!
name: Hello world

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print_hello_from_runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    name: print from bash
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "hello from shell"
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f ejemplo/requirements.txt ]; then pip install -r ejemplo/requirements.txt; fi
      - name: Test with pytest
        run: |
        pytest ejemplo/tests/unit/test_nombres.py -v
        pytest ejemplo/tests/integration/test_integracion.py -v
    #   - uses: actions/checkout@v3
    #   - name: Set up Python 3.8
    #     uses: actions/setup-python@v3
    #     with:
    #       python-version: "3.8"
    #   - name: Install dependencies
    #     run: |
    #       python -m pip install --upgrade pip
    #       pip install flake8
    #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
